# -*- coding: utf-8 -*-
"""wastefp34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kTRu69tpKIS3nWbsGoTGgqNn32uM45CT
"""

import os
import glob
import zipfile
import numpy as np
import cv2
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import Sequence, to_categorical
from tensorflow.keras.models import Sequential, save_model
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# --- 1. Extract dataset ---
ZIP_PATH = "archive (1).zip"
EXTRACT_PATH = "garbage_data"

if not os.path.exists(EXTRACT_PATH):
    with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
        zip_ref.extractall(EXTRACT_PATH)

dataset_dir = os.path.join(EXTRACT_PATH, "Garbage classification", "Garbage classification")

# --- 2. Image Preprocessing Function with Feature Detection (Canny) ---
def preprocess_image_cv2(img_path, target_size=(224, 224)):
    """
    Load an image, resize, detect edges, enhance contrast, blur, and normalize.
    Returns a 4-channel array: BGR normalized + edge map.
    """
    # Read image in BGR format
    img = cv2.imread(img_path)
    # Resize
    img = cv2.resize(img, target_size)

    # Convert to grayscale for edge detection
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Feature detection: Canny edges
    edges = cv2.Canny(gray, threshold1=100, threshold2=200)
    # Normalize edge map to [0,1]
    edges = edges.astype(np.float32) / 255.0

    # Enhance contrast on color image
    img = cv2.convertScaleAbs(img, alpha=1.5, beta=20)
    # Gaussian blur to reduce noise
    img = cv2.GaussianBlur(img, (3, 3), 0)
    # Normalize color image to [0,1]
    img = img.astype(np.float32) / 255.0

    # Stack color image and edges as 4th channel
    combined = np.dstack((img, edges))
    return combined

# --- 3. Data Generator Class ---
class PreprocessingDataGenerator(Sequence):
    def __init__(self, image_paths, labels, batch_size, target_size, num_classes, shuffle=True):
        self.image_paths = image_paths
        self.labels = labels
        self.batch_size = batch_size
        self.target_size = target_size
        self.num_classes = num_classes
        self.shuffle = shuffle
        self.indices = np.arange(len(self.image_paths))
        self.on_epoch_end()

    def __len__(self):
        return int(np.ceil(len(self.image_paths) / self.batch_size))

    def __getitem__(self, idx):
        batch_indices = self.indices[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_paths = [self.image_paths[i] for i in batch_indices]
        batch_labels = [self.labels[i] for i in batch_indices]

        # Preprocess images
        batch_images = [preprocess_image_cv2(path, self.target_size) for path in batch_paths]
        batch_images = np.array(batch_images)
        batch_labels = to_categorical(batch_labels, num_classes=self.num_classes)
        return batch_images, batch_labels

    def on_epoch_end(self):
        if self.shuffle:
            np.random.shuffle(self.indices)

# --- 4. Load image paths and labels ---
def load_image_paths_and_labels(dataset_dir):
    image_paths, labels = [], []
    class_names = sorted([d for d in os.listdir(dataset_dir) if os.path.isdir(os.path.join(dataset_dir, d))])
    class_to_index = {name: idx for idx, name in enumerate(class_names)}

    for class_name in class_names:
        folder = os.path.join(dataset_dir, class_name)
        for filepath in glob.glob(os.path.join(folder, "*")):
            image_paths.append(filepath)
            labels.append(class_to_index[class_name])

    return image_paths, labels, class_names

# --- 5. Prepare Data ---
image_paths, labels, class_names = load_image_paths_and_labels(dataset_dir)
train_paths, val_paths, train_labels, val_labels = train_test_split(
    image_paths, labels, test_size=0.2, stratify=labels, random_state=42
)

batch_size = 32
image_size = (224, 224)
num_classes = len(class_names)

train_gen = PreprocessingDataGenerator(train_paths, train_labels, batch_size, image_size, num_classes)
val_gen = PreprocessingDataGenerator(val_paths, val_labels, batch_size, image_size, num_classes)

# --- 6. Build CNN Model (input channels = 4) ---
def build_model(input_shape, num_classes):
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model

# Instantiate and train
input_shape = image_size + (4,)  # 3 color channels + 1 edge channel
model = build_model(input_shape, num_classes)
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# --- 7. Train Model ---
model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=20,
    callbacks=[early_stopping],
    verbose=1
)

# --- 8. Save Model ---
save_model(model, "garbage_classifier_with_edges.h5")

# --- 9. Visualize Sample Predictions ---
def get_recyclability(label):
    recyclable = {"cardboard", "glass", "metal", "paper", "plastic"}
    non_recyclable = {"trash", "food", "diaper"}
    return "♻ Recyclable" if label in recyclable else "🚫 Non-Recyclable"

# Fetch a batch
test_images, test_labels = val_gen.__getitem__(0)
preds = model.predict(test_images)
pred_labels = np.argmax(preds, axis=1)
true_labels = np.argmax(test_labels, axis=1)

plt.figure(figsize=(12,12))
for i in range(min(16, len(test_images))):
    ax = plt.subplot(4, 4, i+1)
    plt.imshow(test_images[i][:,:,:3])  # show color channels
    tl = class_names[true_labels[i]]
    pl = class_names[pred_labels[i]]
    plt.title(f"T: {tl} ({get_recyclability(tl)})\nP: {pl} ({get_recyclability(pl)})", fontsize=8)
    plt.axis('off')
plt.tight_layout()
plt.show()