# -*- coding: utf-8 -*-
"""WASTEfINALsORTING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V-Yv9fUKVcvQIYvyeY7nt8Hx7utYV4rO
"""

import os
import zipfile
import matplotlib.pyplot as plt
import tensorflow as tf

from tensorflow.keras.applications import MobileNetV2, EfficientNetB0, ResNet50
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

import zipfile
import os

zip_path = "garbage.zip"
extract_to = "garbage_data"

# Check if zip file is valid
if zipfile.is_zipfile(zip_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_to)
    print("Zip extraction completed.")
else:
    print("❌ The file is not a valid zip file!")

# Check extracted folder structure
for root, dirs, files in os.walk(extract_to):
    print("Top-level folder:", root)
    break

# Update this based on the printed path
dataset_dir = os.path.join(extract_to, "Garbage classification", "Garbage classification")
print("Dataset directory set to:", dataset_dir)

image_size = (150, 150)
batch_size  = 32
epochs = 10

import zipfile
import os

# Unzip the file
with zipfile.ZipFile("archive (1).zip", 'r') as zip_ref:
    zip_ref.extractall("garbage_data")

dataset_dir = "garbage_data/Garbage classification/Garbage classification"

def prepare_dataset(zip_path="archive (1).zip", extract_path="garbage_data"):
    if not os.path.exists(extract_path):
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_path)
    return os.path.join(extract_path, "Garbage classification", "Garbage classification")

dataset_dir = prepare_dataset()
image_size = (224, 224)
batch_size = 32
epochs = 2  # Reduce for faster testing

def get_data_generators(dataset_dir, image_size, batch_size):
    datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

    train = datagen.flow_from_directory(
        dataset_dir, target_size=image_size, batch_size=batch_size,
        class_mode='categorical', subset='training'
    )

    val = datagen.flow_from_directory(
        dataset_dir, target_size=image_size, batch_size=batch_size,
        class_mode='categorical', subset='validation'
    )
    return train, val

train_generator, val_generator = get_data_generators(dataset_dir, image_size, batch_size)

def build_model(base_model_fn, name, input_shape, num_classes):
    base_model = base_model_fn(input_shape=input_shape, include_top=False, weights='imagenet')
    base_model.trainable = False

    inputs = Input(shape=input_shape)
    x = base_model(inputs, training=False)
    x = GlobalAveragePooling2D()(x)
    x = Dense(128, activation='relu')(x)
    outputs = Dense(num_classes, activation='softmax')(x)

    model = Model(inputs, outputs, name=name)
    model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])
    return model

def plot_history(histories, labels):
    plt.figure(figsize=(14, 6))
    for history, label in zip(histories, labels):
        plt.plot(history.history['val_accuracy'], label=f'{label} (Val Acc)')
    plt.title("Validation Accuracy per Epoch")
    plt.xlabel("Epochs")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.grid()
    plt.show()

def train_models(model_fns, model_names, image_size, train_gen, val_gen, epochs):
    histories = []
    accuracies = {}

    for fn, name in zip(model_fns, model_names):
        print(f"\nTraining {name}...")
        model = build_model(fn, name, image_size + (3,), train_gen.num_classes)
        history = model.fit(train_gen, validation_data=val_gen, epochs=epochs, verbose=1)
        histories.append(history)
        accuracies[name] = history.history['val_accuracy'][-1]

    return histories, accuracies

model_fns = [MobileNetV2, EfficientNetB0, ResNet50]
model_names = ['MobileNetV2', 'EfficientNetB0', 'ResNet50']

train_histories, baseline_accuracies = train_models(model_fns, model_names, image_size, train_generator, val_generator, epochs)
plot_history(train_histories, model_names)

import matplotlib.pyplot as plt

def plot_model_accuracies(accuracies_dict, title="Model Accuracy Comparison"):
    names = list(accuracies_dict.keys())
    values = list(accuracies_dict.values())

    plt.figure(figsize=(8, 6))
    bars = plt.bar(names, values, color=['skyblue', 'lightgreen', 'salmon'])

    # Annotate bars with accuracy values
    for bar, acc in zip(bars, values):
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2.0, yval + 0.01, f'{acc:.2f}', ha='center', va='bottom', fontsize=12)

    plt.ylim(0, 1.1)
    plt.ylabel("Validation Accuracy")
    plt.title(title)
    plt.grid(axis='y', linestyle='--', alpha=0.6)
    plt.show()

# Call the function
plot_model_accuracies(baseline_accuracies)

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import save_model

# --- 1. Plot training histories (assuming plot_history already exists) ---
# Already done by: plot_history(train_histories, model_names)

# --- 2. Select best model based on validation accuracy ---
best_model_idx = np.argmax(list(baseline_accuracies.values()))
best_model_name = model_names[best_model_idx]
best_model_fn = model_fns[best_model_idx]

print(f"\nBest model is: {best_model_name} with validation accuracy: {baseline_accuracies[best_model_name]:.4f}")

# --- 3. Re-train best model (optional but recommended before predictions) ---
model = build_model(best_model_fn, best_model_name, image_size + (3,), train_generator.num_classes)
model.fit(train_generator, validation_data=val_generator, epochs=epochs, verbose=1)

# Save the best model (optional)
save_model(model, f"{best_model_name}_garbage_classifier.h5")

# --- 4. Prepare class info for predictions ---
class_indices = train_generator.class_indices
classes = [cls for cls, idx in sorted(class_indices.items(), key=lambda x: x[1])]

# Define recyclable/non-recyclable categories (customize this based on your dataset)
recyclable_classes = {"cardboard", "glass", "metal", "paper", "plastic"}
non_recyclable_classes = {"trash", "food", "diaper"}  # Add/modify as needed

def get_recyclability(label):
    if label in recyclable_classes:
        return "♻ Recyclable"
    elif label in non_recyclable_classes:
        return "🚫 Non-Recyclable"
    else:
        return "❓ Unknown"

# --- 5. Fetch a batch of validation data to visualize predictions ---
test_images, test_labels = next(val_generator)

# Make predictions
predictions = model.predict(test_images)
predicted_labels = np.argmax(predictions, axis=1)
true_labels = np.argmax(test_labels, axis=1)

# --- 6. Visualization function ---
def visualize_predictions(test_images, true_labels, predicted_labels, class_names, num_images=20):
    plt.figure(figsize=(18, 18))
    for i in range(num_images):
        ax = plt.subplot(5, 5, i + 1)
        img = test_images[i]
        true_label = class_names[true_labels[i]]
        pred_label = class_names[predicted_labels[i]]

        true_recycle = get_recyclability(true_label)
        pred_recycle = get_recyclability(pred_label)

        plt.imshow(img)
        plt.title(f"Pred: {pred_label}\n({pred_recycle})\nTrue: {true_label}\n({true_recycle})", fontsize=8)
        plt.axis("off")
    plt.tight_layout()
    plt.show()

# --- 7. Visualize ---
visualize_predictions(test_images, true_labels, predicted_labels, classes, num_images=20)

from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models
import keras_tuner as kt

def build_mobilenetv2_model(hp):
    base_model = MobileNetV2(include_top=False, input_shape=image_size + (3,), weights='imagenet')
    base_model.trainable = False  # Optionally fine-tune later

    model = models.Sequential()
    model.add(base_model)
    model.add(layers.GlobalAveragePooling2D())

    # Tune dropout
    hp_dropout = hp.Float('dropout', 0.2, 0.5, step=0.1)
    model.add(layers.Dropout(hp_dropout))

    model.add(layers.Dense(train_generator.num_classes, activation='softmax'))

    # Tune learning rate
    hp_lr = hp.Choice('learning_rate', [1e-2, 1e-3, 1e-4])

    model.compile(optimizer=Adam(learning_rate=hp_lr),
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    return model

# Set up Keras Tuner
tuner = kt.Hyperband(
    build_mobilenetv2_model,
    objective='val_accuracy',
    max_epochs=5,
    factor=3,
    directory='tuner_results',
    project_name='MobileNetV2_tuning'
)

# Optional: early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=2)

# Run search
tuner.search(train_generator, validation_data=val_generator, epochs=5, callbacks=[early_stopping])



# Get the best hyperparameters
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

# Print the best hyperparameters
print(f"Best Dropout Rate: {best_hps.get('dropout')}")
print(f"Best Learning Rate: {best_hps.get('learning_rate')}")

# Build the best model with the best hyperparameters
model = tuner.hypermodel.build(best_hps)

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=10,  # You can increase this as needed
    callbacks=[early_stopping]
)

# Access previously trained baseline accuracy
baseline_mobilenetv2_acc = baseline_accuracies['MobileNetV2']

# Print both accuracies
print("Baseline MobileNetV2 Accuracy: {:.2f}%".format(baseline_mobilenetv2_acc * 100))
print("Tuned MobileNetV2 Accuracy   : {:.2f}%".format(tuned_mobilenetv2_acc * 100))

import matplotlib.pyplot as plt

# Accuracy comparison bar plot
labels = ['Baseline', 'Tuned']
accuracies = [baseline_mobilenetv2_acc * 100, tuned_mobilenetv2_acc * 100]

plt.figure(figsize=(6, 4))
bars = plt.bar(labels, accuracies, color=['skyblue', 'orange'])
plt.ylim(0, 100)
plt.title('MobileNetV2 Accuracy Comparison')
plt.ylabel('Validation Accuracy (%)')

# Annotate bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2.0, yval + 1, f'{yval:.2f}%', ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Get class names from generator
class_indices = train_generator.class_indices
classes = [cls for cls, idx in sorted(class_indices.items(), key=lambda x: x[1])]

# Fetch a batch of validation data to visualize predictions
test_images, test_labels = next(validation_generator)

# Use tuned model for prediction
predictions = tuned_mobilenetv2_model.predict(test_images)

# Convert predictions and true labels to class indices
predicted_labels = np.argmax(predictions, axis=1)
true_labels = np.argmax(test_labels, axis=1)

# Define the visualization function
def visualize_predictions(test_images, true_labels, predicted_labels, class_names, num_images=20):
    plt.figure(figsize=(15, 15))
    for i in range(num_images):
        ax = plt.subplot(5, 5, i + 1)
        img = test_images[i]
        true_label = class_names[true_labels[i]]
        pred_label = class_names[predicted_labels[i]]
        plt.imshow(img)
        plt.title(f"Pred: {pred_label}\nTrue: {true_label}", fontsize=9)
        plt.axis("off")
    plt.tight_layout()
    plt.show()

# Visualize the tuned model's predictions
visualize_predictions(test_images, true_labels, predicted_labels, classes, num_images=20)

pip install tensorflow keras-tuner

def tuner_model_builder(hp, base_model_fn, image_size, num_classes):
    base_model = base_model_fn(input_shape=image_size + (3,), include_top=False, weights='imagenet')
    base_model.trainable = False

    inputs = Input(shape=image_size + (3,))
    x = base_model(inputs, training=False)
    x = GlobalAveragePooling2D()(x)
    x = Dense(hp.Int("units", 64, 256, step=64), activation="relu")(x)
    outputs = Dense(num_classes, activation='softmax')(x)

    model = Model(inputs, outputs)
    model.compile(
        optimizer=Adam(learning_rate=hp.Choice("lr", [1e-2, 1e-3, 1e-4])),
        loss='categorical_crossentropy',
        metrics=["accuracy"]
    )
    return model

import keras_tuner as kt

def tune_single_model(fn, name, image_size, train_gen, val_gen):
    print(f"\nTuning {name}...")
    tuner = kt.Hyperband(
        lambda hp: tuner_model_builder(hp, fn, image_size, train_gen.num_classes),
        objective="val_accuracy",
        max_epochs=3,  # Reduce for quicker tuning
        factor=3,
        directory="tuner_results",
        project_name=name
    )

    tuner.search(train_gen, validation_data=val_gen, epochs=3, verbose=0)
    best_hp = tuner.get_best_hyperparameters(1)[0]
    best_model = tuner.hypermodel.build(best_hp)

    history = best_model.fit(train_gen, validation_data=val_gen, epochs=3, verbose=0)
    final_val_acc = history.history['val_accuracy'][-1]
    return final_val_acc

def build_and_train_model(base_model_fn, name, image_size, train_gen, val_gen):
    print(f"\nTraining {name}...")

    # Base Model
    base_model = base_model_fn(include_top=False, weights='imagenet', input_shape=(*image_size, 3))
    base_model.trainable = False  # Freeze base model for speed

    # Add custom classification head
    model = tf.keras.Sequential([
        base_model,
        tf.keras.layers.GlobalAveragePooling2D(),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(train_gen.num_classes, activation='softmax')
    ])

    # Compile
    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    # Train
    history = model.fit(train_gen, validation_data=val_gen, epochs=2, verbose=1)  # Just 2 epochs for speed
    final_val_acc = history.history['val_accuracy'][-1]
    return final_val_acc

# Define image size and generators if not already done
image_size = (224, 224)

# Run training for each model
mobilenet_acc = build_and_train_model(tf.keras.applications.MobileNetV2, "MobileNetV2", image_size, train_generator, val_generator)
efficientnet_acc = build_and_train_model(tf.keras.applications.EfficientNetB0, "EfficientNetB0", image_size, train_generator, val_generator)
resnet_acc = build_and_train_model(tf.keras.applications.ResNet50, "ResNet50", image_size, train_generator, val_generator)

# Combine results
accuracies = {
    "MobileNetV2": mobilenet_acc,
    "EfficientNetB0": efficientnet_acc,
    "ResNet50": resnet_acc
}





import numpy as np
import matplotlib.pyplot as plt

def get_class_names(generator):
    """Extract ordered class names from the generator."""
    class_indices = generator.class_indices
    return [cls for cls, idx in sorted(class_indices.items(), key=lambda x: x[1])]

def get_predictions(model, generator):
    """Fetch a batch of data and make predictions."""
    test_images, test_labels = next(generator)
    predictions = model.predict(test_images)
    predicted_labels = np.argmax(predictions, axis=1)
    true_labels = np.argmax(test_labels, axis=1)
    return test_images, true_labels, predicted_labels

def visualize_predictions(images, true_labels, predicted_labels, class_names, num_images=20):
    """Plot sample predictions with ground truth and predicted labels."""
    plt.figure(figsize=(15, 15))
    for i in range(num_images):
        ax = plt.subplot(5, 5, i + 1)
        img = images[i]
        true_label = class_names[true_labels[i]]
        pred_label = class_names[predicted_labels[i]]
        plt.imshow(img)
        plt.title(f"Pred: {pred_label}\nTrue: {true_label}", fontsize=9, color='green' if pred_label == true_label else 'red')
        plt.axis("off")
    plt.tight_layout()
    plt.show()



